/********************************************************************
* ../gcrSelectRootData/gcrSelectRootData_rootcint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../gcrSelectRootData/gcrSelectRootData_rootcint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablegcrSelectRootData_rootcint();
extern void G__cpp_setup_inheritancegcrSelectRootData_rootcint();
extern void G__cpp_setup_typetablegcrSelectRootData_rootcint();
extern void G__cpp_setup_memvargcrSelectRootData_rootcint();
extern void G__cpp_setup_globalgcrSelectRootData_rootcint();
extern void G__cpp_setup_memfuncgcrSelectRootData_rootcint();
extern void G__cpp_setup_funcgcrSelectRootData_rootcint();
extern void G__set_cpp_environmentgcrSelectRootData_rootcint();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "../../../reconRootData/v9r7/reconRootData/CalXtalRecData.h"
#include "../gcrSelectRootData/GcrSelectedXtal.h"
#include "../gcrSelectRootData/GcrSelectEvent.h"
#include "../gcrSelectRootData/GcrSelectVals.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TClass;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TBuffer;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMemberInspector;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TObject;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TObjArray;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_maplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_TVector3;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_CalXtalId;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_vectorlECalRangeRecDatacOallocatorlECalRangeRecDatagRsPgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_reverse_iteratorlEvectorlECalRangeRecDatacOallocatorlECalRangeRecDatagRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_GcrSelectedXtal;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_GcrSelectedXtalcLcLXFACE_BITPOS;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_GcrSelectVals;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_GcrSelect;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_GcrSelectEvent;
extern G__linked_taginfo G__gcrSelectRootData_rootcintLN_GcrSelectEventcLcLEventFlags;

/* STUB derived class for protected member access */
